export default {
  light: {
    principalBorda: '#2E86AB',
    principalPreenchimento: '#A8D0E6',
    secundarioBorda: '#F2A365',
    secundarioPreenchimento: '#F9D5B4',
    sucessoBorda: '#3AA655',
    sucessoPreenchimento: '#B0EACD',
    alertaBorda: '#E94F37',
    alertaPreenchimento: '#F5A8A0',
    textoPrincipal: '#222',
    textoSecundario: '#666',
    cinzaClaro: '#DDD',
    background: '#FFF',
  },
  dark: {
    principalBorda: '#63B3D7',
    principalPreenchimento: '#305E71',
    secundarioBorda: '#F7B88A',
    secundarioPreenchimento: '#8B6C55',
    sucessoBorda: '#6ED89F',
    sucessoPreenchimento: '#355C49',
    alertaBorda: '#F08070',
    alertaPreenchimento: '#6A3B38',
    textoPrincipal: '#222',
    // textoPrincipal: '#EEE',
    textoSecundario: '#AAA',
    cinzaClaro: '#444',
    background: '#fff',
    // background: '#121212',
  },
};
